import type { NativeBlock } from '@thelacanians/vue-native-sfc-parser'
import type { GeneratedFile, CodegenOptions } from '../types'
import * as path from 'path'

/**
 * Generate Kotlin module file from a native block
 */
export function generateKotlinFile(
  block: NativeBlock,
  options: CodegenOptions = {},
): GeneratedFile {
  const { includeHeader = true } = options

  // Extract class name from content
  const className = extractClassName(block.content, block.sourceFile)
  const moduleName = extractModuleName(block.content, className)

  // Generate the output path
  const outputDir = options.androidOutputDir || 'native/android/VueNativeCore/src/main/kotlin/com/vuenative/core/GeneratedModules'
  const outputPath = path.join(outputDir, `${className}.kt`)

  // Generate the Kotlin code
  const content = generateKotlinContent(block, moduleName, includeHeader)

  return {
    platform: block.platform,
    language: 'kotlin',
    content,
    outputPath,
    sourceBlock: block,
  }
}

/**
 * Generate Kotlin module registration code
 */
export function generateKotlinRegistration(
  blocks: NativeBlock[],
): string {
  const androidBlocks = blocks.filter(block => block.platform === 'android')

  const registrations = androidBlocks.map((block) => {
    const className = extractClassName(block.content, block.sourceFile)
    return `    registerAndInitialize(${className}(), bridge, context)`
  }).join('\n')

  const generatedModuleImport = androidBlocks.length > 0
    ? 'import com.vuenative.core.GeneratedModules.*\n\n'
    : ''
  return `// Auto-generated module registration
// DO NOT EDIT - Generated by vue-native-codegen

package com.vuenative.core

${generatedModuleImport}
fun NativeModuleRegistry.registerGeneratedModules(context: android.content.Context, bridge: NativeBridge) {
${registrations || '    // No generated Android modules.'}
}`
}

/**
 * Generate the complete Kotlin file content
 */
function generateKotlinContent(
  block: NativeBlock,
  moduleName: string,
  includeHeader: boolean,
): string {
  const header = includeHeader ? generateKotlinHeader(block) : ''
  const source = stripPackageDeclaration(decodeEntities(block.content)).trim()

  return `${header}
package com.vuenative.core.GeneratedModules

import android.content.Context
import com.vuenative.core.NativeBridge
import com.vuenative.core.NativeModule

/// Auto-generated native module from ${block.componentName}.vue
/// Platform: ${block.platform}
/// Module: ${moduleName}
${source}
`
}

/**
 * Generate Kotlin file header
 */
function generateKotlinHeader(block: NativeBlock): string {
  return `// ────────────────────────────────────────────────────────────────────────────────
//  Auto-Generated Code
// ────────────────────────────────────────────────────────────────────────────────
//
//  Generated from: ${path.basename(block.sourceFile)}
//  Component: ${block.componentName}
//  Platform: ${block.platform}
//  Language: Kotlin
//
//  ⚠️  WARNING: This file is auto-generated. DO NOT EDIT MANUALLY.
//      Changes will be overwritten by the code generator.
//
//  Source: ${block.sourceFile}
// ────────────────────────────────────────────────────────────────────────────────
`
}

/**
 * Extract class name from Kotlin code
 * Looks for: class ClassName: NativeModule
 */
function extractClassName(content: string, sourceFile: string): string {
  const match = content.match(/class\s+(\w+)\s*:\s*NativeModule/)
  if (!match) {
    // Fallback to component name
    const fallback = `${path.basename(sourceFile, '.vue')}Module`
    console.warn(`[vue-native-codegen] Warning: Could not extract class name from ${sourceFile}. Using fallback: ${fallback}`)
    return fallback
  }
  return match[1]
}

/**
 * Extract module name from Kotlin code
 * Looks for: override val moduleName: String = "Name"
 */
function extractModuleName(content: string, className: string): string {
  // Try to extract from moduleName property
  const match = content.match(/override\s+val\s+moduleName\s*:\s*String\s*=\s*"([^"]+)"/)
  if (match) {
    return match[1]
  }

  // Fallback to class name without "Module" suffix
  const fallback = className.replace(/Module$/, '')
  return fallback
}

function stripPackageDeclaration(content: string): string {
  return content.replace(/^\s*package\s+[\w.]+\s*\n+/, '')
}

function decodeEntities(content: string): string {
  return content
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
}
