import type { NativeBlock } from '@thelacanians/vue-native-sfc-parser'
import type { GeneratedFile, CodegenOptions } from '../types'
import * as path from 'path'

/**
 * Generate Kotlin module file from a native block
 */
export function generateKotlinFile(
  block: NativeBlock,
  options: CodegenOptions = {},
): GeneratedFile {
  const { includeHeader = true } = options

  // Extract class name from content
  const className = extractClassName(block.content, block.sourceFile)
  const moduleName = extractModuleName(block.content, className)

  // Generate the output path
  const outputDir = options.androidOutputDir || 'native/android/VueNativeCore/src/main/kotlin/com/vuenative/core/GeneratedModules'
  const outputPath = path.join(outputDir, `${className}.kt`)

  // Generate the Kotlin code
  const content = generateKotlinContent(block, className, moduleName, includeHeader)

  return {
    platform: block.platform,
    language: 'kotlin',
    content,
    outputPath,
    sourceBlock: block,
  }
}

/**
 * Generate Kotlin module registration code
 */
export function generateKotlinRegistration(
  blocks: NativeBlock[],
): string {
  const androidBlocks = blocks.filter(block => block.platform === 'android')

  const registrations = androidBlocks.map((block) => {
    const className = extractClassName(block.content, block.sourceFile)
    const moduleName = extractModuleName(block.content, className)
    return `    register("${moduleName}", ${className}())`
  }).join('\n')

  return `// Auto-generated module registration
// DO NOT EDIT - Generated by vue-native-codegen

fun registerGeneratedModules() {
${registrations}
}`
}

/**
 * Generate the complete Kotlin file content
 */
function generateKotlinContent(
  block: NativeBlock,
  className: string,
  moduleName: string,
  includeHeader: boolean,
): string {
  const header = includeHeader ? generateKotlinHeader(block) : ''

  return `${header}
package com.vuenative.core.GeneratedModules

import com.vuenative.core.Bridge.NativeModule

/// Auto-generated native module from ${block.componentName}.vue
/// Platform: ${block.platform}
class ${className}: NativeModule {
    override val moduleName: String = "${moduleName}"
    
    // User-provided implementation
${indent(block.content, 4)}
}
`
}

/**
 * Generate Kotlin file header
 */
function generateKotlinHeader(block: NativeBlock): string {
  return `// ────────────────────────────────────────────────────────────────────────────────
//  Auto-Generated Code
// ────────────────────────────────────────────────────────────────────────────────
//
//  Generated from: ${path.basename(block.sourceFile)}
//  Component: ${block.componentName}
//  Platform: ${block.platform}
//  Language: Kotlin
//
//  ⚠️  WARNING: This file is auto-generated. DO NOT EDIT MANUALLY.
//      Changes will be overwritten by the code generator.
//
//  Source: ${block.sourceFile}
//  Generated: ${new Date().toISOString()}
//
// ────────────────────────────────────────────────────────────────────────────────
`
}

/**
 * Extract class name from Kotlin code
 * Looks for: class ClassName: NativeModule
 */
function extractClassName(content: string, sourceFile: string): string {
  const match = content.match(/class\s+(\w+)\s*:\s*NativeModule/)
  if (!match) {
    // Fallback to component name
    const fallback = `${path.basename(sourceFile, '.vue')}Module`
    console.warn(`[vue-native-codegen] Warning: Could not extract class name from ${sourceFile}. Using fallback: ${fallback}`)
    return fallback
  }
  return match[1]
}

/**
 * Extract module name from Kotlin code
 * Looks for: override val moduleName: String = "Name"
 */
function extractModuleName(content: string, className: string): string {
  // Try to extract from moduleName property
  const match = content.match(/override\s+val\s+moduleName\s*:\s*String\s*=\s*"([^"]+)"/)
  if (match) {
    return match[1]
  }

  // Fallback to class name without "Module" suffix
  const fallback = className.replace(/Module$/, '')
  return fallback
}

/**
 * Indent all lines in a string
 */
function indent(text: string, spaces: number): string {
  const prefix = ' '.repeat(spaces)
  return text
    .split('\n')
    .map(line => line.trim() ? prefix + line : line)
    .join('\n')
}
