import type { NativeBlock } from '@thelacanians/vue-native-sfc-parser'
import type { GeneratedFile, CodegenOptions } from '../types'
import * as path from 'path'

/**
 * Generate Swift module file from a native block
 */
export function generateSwiftFile(
  block: NativeBlock,
  options: CodegenOptions = {},
): GeneratedFile {
  const { includeHeader = true } = options

  // Extract module name from content (look for "class X: NativeModule")
  const className = extractClassName(block.content, block.sourceFile)
  const moduleName = extractModuleName(block.content, className)

  // Generate the output path
  const outputDir = options.iosOutputDir || 'native/ios/VueNativeCore/Sources/VueNativeCore/GeneratedModules'
  const outputPath = path.join(outputDir, `${className}.swift`)

  // Generate the Swift code
  const content = generateSwiftContent(block, className, moduleName, includeHeader)

  return {
    platform: block.platform,
    language: 'swift',
    content,
    outputPath,
    sourceBlock: block,
  }
}

/**
 * Generate Swift module registration code
 */
export function generateSwiftRegistration(
  blocks: NativeBlock[],
  _options: CodegenOptions = {},
): string {
  const iosBlocks = blocks.filter(b => b.platform === 'ios' || b.platform === 'macos')

  const registrations = iosBlocks.map((block) => {
    const className = extractClassName(block.content, block.sourceFile)
    const moduleName = extractModuleName(block.content, className)
    return `        register("${moduleName}", module: ${className}())`
  }).join('\n')

  return `// Auto-generated module registration
// DO NOT EDIT - Generated by vue-native-codegen

func registerGeneratedModules() {
${registrations}
}`
}

/**
 * Generate the complete Swift file content
 */
function generateSwiftContent(
  block: NativeBlock,
  className: string,
  moduleName: string,
  includeHeader: boolean,
): string {
  const header = includeHeader ? generateSwiftHeader(block) : ''

  return `${header}
import Foundation
import VueNativeCore

/// Auto-generated native module from ${block.componentName}.vue
/// Platform: ${block.platform}
final class ${className}: NativeModule {
    var moduleName: String { "${moduleName}" }
    
    // User-provided implementation
${indent(block.content, 4)}
}
`
}

/**
 * Generate Swift file header
 */
function generateSwiftHeader(block: NativeBlock): string {
  return `// ────────────────────────────────────────────────────────────────────────────────
//  Auto-Generated Code
// ────────────────────────────────────────────────────────────────────────────────
//
//  Generated from: ${path.basename(block.sourceFile)}
//  Component: ${block.componentName}
//  Platform: ${block.platform}
//  Language: Swift
//
//  ⚠️  WARNING: This file is auto-generated. DO NOT EDIT MANUALLY.
//      Changes will be overwritten by the code generator.
//
//  Source: ${block.sourceFile}
//  Generated: ${new Date().toISOString()}
//
// ────────────────────────────────────────────────────────────────────────────────
`
}

/**
 * Extract class name from Swift code
 * Looks for: class ClassName: NativeModule
 */
function extractClassName(content: string, sourceFile: string): string {
  const match = content.match(/class\s+(\w+)\s*:\s*NativeModule/)
  if (!match) {
    // Fallback to component name
    const fallback = `${path.basename(sourceFile, '.vue')}Module`
    console.warn(`[vue-native-codegen] Warning: Could not extract class name from ${sourceFile}. Using fallback: ${fallback}`)
    return fallback
  }
  return match[1]
}

/**
 * Extract module name from Swift code
 * Looks for: var moduleName: String { "Name" }
 */
function extractModuleName(content: string, className: string): string {
  // Try to extract from moduleName property
  const match = content.match(/var\s+moduleName\s*:\s*String\s*\{\s*"([^"]+)"\s*\}/)
  if (match) {
    return match[1]
  }

  // Fallback to class name without "Module" suffix
  const fallback = className.replace(/Module$/, '')
  return fallback
}

/**
 * Indent all lines in a string
 */
function indent(text: string, spaces: number): string {
  const prefix = ' '.repeat(spaces)
  return text
    .split('\n')
    .map(line => line.trim() ? prefix + line : line)
    .join('\n')
}
