import type { NativeBlock } from '@thelacanians/vue-native-sfc-parser'
import type { GeneratedFile, CodegenOptions } from '../types'
import * as path from 'path'

/**
 * Generate Swift module file from a native block
 */
export function generateSwiftFile(
  block: NativeBlock,
  options: CodegenOptions = {},
): GeneratedFile {
  const { includeHeader = true } = options

  // Extract module metadata from the user-provided class.
  const className = extractClassName(block.content, block.sourceFile)
  const moduleName = extractModuleName(block.content, className)

  const outputDir = block.platform === 'macos'
    ? options.macosOutputDir || 'native/macos/VueNativeMacOS/Sources/VueNativeMacOS/GeneratedModules'
    : options.iosOutputDir || 'native/ios/VueNativeCore/Sources/VueNativeCore/GeneratedModules'
  const outputPath = path.join(outputDir, `${className}.swift`)

  const content = generateSwiftContent(block, moduleName, includeHeader)

  return {
    platform: block.platform,
    language: 'swift',
    content,
    outputPath,
    sourceBlock: block,
  }
}

/**
 * Generate Swift module registration code
 */
export function generateSwiftRegistration(
  blocks: NativeBlock[],
  options: CodegenOptions & { platform?: 'ios' | 'macos' } = {},
): string {
  const platform = options.platform ?? (blocks.every(b => b.platform === 'macos') ? 'macos' : 'ios')
  const platformBlocks = blocks.filter(b => b.platform === platform)

  const registrations = platformBlocks.map((block) => {
    const className = extractClassName(block.content, block.sourceFile)
    return `        register(${className}())`
  }).join('\n')

  const imports = platform === 'macos'
    ? 'import AppKit\nimport VueNativeShared'
    : 'import Foundation\nimport UIKit'

  return `// Auto-generated module registration
// DO NOT EDIT - Generated by vue-native-codegen

${imports}

@MainActor
extension NativeModuleRegistry {
    func registerGeneratedModules() {
${registrations}
    }
}`
}

/**
 * Generate the complete Swift file content
 */
function generateSwiftContent(
  block: NativeBlock,
  moduleName: string,
  includeHeader: boolean,
): string {
  const header = includeHeader ? generateSwiftHeader(block) : ''
  const imports = block.platform === 'macos'
    ? 'import Foundation\nimport AppKit\nimport VueNativeShared'
    : 'import Foundation\nimport UIKit'

  return `${header}
${imports}

/// Auto-generated native module from ${block.componentName}.vue
/// Platform: ${block.platform}
/// Module: ${moduleName}
${decodeEntities(block.content).trim()}
`
}

/**
 * Generate Swift file header
 */
function generateSwiftHeader(block: NativeBlock): string {
  return `// ────────────────────────────────────────────────────────────────────────────────
//  Auto-Generated Code
// ────────────────────────────────────────────────────────────────────────────────
//
//  Generated from: ${path.basename(block.sourceFile)}
//  Component: ${block.componentName}
//  Platform: ${block.platform}
//  Language: Swift
//
//  ⚠️  WARNING: This file is auto-generated. DO NOT EDIT MANUALLY.
//      Changes will be overwritten by the code generator.
//
//  Source: ${block.sourceFile}
// ────────────────────────────────────────────────────────────────────────────────
`
}

/**
 * Extract class name from Swift code
 * Looks for: class ClassName: NativeModule
 */
function extractClassName(content: string, sourceFile: string): string {
  const match = content.match(/class\s+(\w+)\s*:\s*NativeModule/)
  if (!match) {
    // Fallback to component name
    const fallback = `${path.basename(sourceFile, '.vue')}Module`
    console.warn(`[vue-native-codegen] Warning: Could not extract class name from ${sourceFile}. Using fallback: ${fallback}`)
    return fallback
  }
  return match[1]
}

/**
 * Extract module name from Swift code
 * Looks for: var moduleName: String { "Name" }
 */
function extractModuleName(content: string, className: string): string {
  // Try to extract from moduleName property
  const match = content.match(/var\s+moduleName\s*:\s*String\s*\{\s*"([^"]+)"\s*\}/)
  if (match) {
    return match[1]
  }

  // Fallback to class name without "Module" suffix
  const fallback = className.replace(/Module$/, '')
  return fallback
}

function decodeEntities(content: string): string {
  return content
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
}
